language: php
os:
  - linux
sudo: false
php:
# - 5.3 (doesn't recognize $var=[], only recognizes $var=array())
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
matrix:
  allow_failures:
    - php: nightly
services:
  - mysql
before_script:
  - cp etc/config.sample.json etc/config.redux.json
script:
  - bash -c 'set -e;for file in $(find . -type f -regextype posix-extended -regex .*\.\(php\|dm\) -print); do php -e -l -f "$file"; done'
